<?php
/**
 * Plugin uninstall routine.
 *
 * @package Leadealer
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

/**
 * Unschedule every Leadealer job for the current site.
 *
 * @return void
 */
function leadealer_uninstall_unschedule_site() {
	wp_unschedule_hook( 'leadealer_daily_cleanup' );
	wp_unschedule_hook( 'leadealer_retry_mail' );
	wp_unschedule_hook( 'leadealer_mail_watchdog' );
	wp_unschedule_hook( 'leadealer_delivery_recovery' );
}

/**
 * Return plugin-owned attachment directories for the current site.
 *
 * Includes the legacy predictable directory for clean upgrades from 0.7.0.
 *
 * @return string[]
 */
function leadealer_uninstall_storage_dirs() {
	$upload_dir = wp_upload_dir();
	if ( ! is_array( $upload_dir ) || ! empty( $upload_dir['error'] ) || empty( $upload_dir['basedir'] ) || ! is_string( $upload_dir['basedir'] ) ) {
		return array();
	}

	$base_dir = wp_normalize_path( $upload_dir['basedir'] );
	if ( '' === $base_dir || ( '/' !== substr( $base_dir, 0, 1 ) && 1 !== preg_match( '#^[A-Za-z]:/#', $base_dir ) ) ) {
		return array();
	}

	$secret = get_option( 'leadealer_secret' );
	if ( ! is_string( $secret ) || strlen( $secret ) < 32 ) {
		$secret = wp_salt( 'auth' );
	}

	$suffix = substr( hash_hmac( 'sha256', 'leadealer-private-upload-directory', $secret ), 0, 24 );

	return array(
		trailingslashit( $base_dir ) . 'leadealer-private-' . $suffix,
		trailingslashit( $base_dir ) . 'leadealer-attachments',
	);
}

/**
 * Check whether a basename matches a filename generated by Leadealer.
 *
 * @param string $filename Candidate basename.
 * @return bool
 */
function leadealer_uninstall_valid_attachment_name( $filename ) {
	if ( ! is_string( $filename ) || basename( $filename ) !== $filename ) {
		return false;
	}

	return 1 === preg_match( '/^(?:[a-f0-9]{48}|[A-Za-z0-9]{32})\.(?:jpg|jpeg|png|webp)$/', $filename );
}

/**
 * Delete only plugin-owned files from one hardened attachment directory.
 *
 * @param string $dir Absolute directory path.
 * @return void
 */
function leadealer_uninstall_delete_storage_dir( $dir ) {
	if ( ! is_string( $dir ) || ! is_dir( $dir ) || is_link( $dir ) ) {
		return;
	}

	$files = scandir( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_scandir -- Fixed plugin-owned directory cleanup during uninstall.
	if ( ! is_array( $files ) ) {
		return;
	}

	$guard_files = array( '.htaccess', 'web.config', 'index.php', 'index.html' );
	foreach ( $files as $filename ) {
		if ( '.' === $filename || '..' === $filename ) {
			continue;
		}
		if ( ! in_array( $filename, $guard_files, true ) && ! leadealer_uninstall_valid_attachment_name( $filename ) ) {
			continue;
		}

		$path = trailingslashit( $dir ) . $filename;
		if ( is_file( $path ) && ! is_link( $path ) ) {
			wp_delete_file( $path );
		}
	}

	$remaining = scandir( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_scandir -- Verify the fixed plugin-owned directory is empty before removing it.
	if ( is_array( $remaining ) && 2 === count( $remaining ) ) {
		rmdir( $dir ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir -- Remove an empty, fixed plugin-owned directory during uninstall.
	}
}

/**
 * Remove all plugin-owned data for the current site.
 *
 * @return void
 */
function leadealer_uninstall_delete_site_data() {
	global $wpdb;

	do {
		$form_ids = get_posts(
			array(
				'post_type'      => 'leadealer_form',
				'post_status'    => 'any',
				'posts_per_page' => 100,
				'fields'         => 'ids',
			)
		);

		foreach ( $form_ids as $form_id ) {
			wp_delete_post( $form_id, true );
		}

		$found_count = count( $form_ids );
	} while ( 100 === $found_count );

	foreach ( leadealer_uninstall_storage_dirs() as $dir ) {
		leadealer_uninstall_delete_storage_dir( $dir );
	}

	$tables = array(
		$wpdb->prefix . 'leadealer_uploads',
		$wpdb->prefix . 'leadealer_entries',
		$wpdb->prefix . 'leadealer_events',
		$wpdb->prefix . 'leadealer_pow_used',
		$wpdb->prefix . 'leadealer_rate_limits',
	);

	foreach ( $tables as $table ) {
		$wpdb->query( $wpdb->prepare( 'DROP TABLE IF EXISTS %i', $table ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.SchemaChange,WordPress.DB.DirectDatabaseQuery.NoCaching -- Explicit uninstall of a plugin-owned table.
	}

	delete_option( 'leadealer_secret' );
	delete_option( 'leadealer_db_version' );
	delete_option( 'leadealer_pow_difficulty' );
	delete_option( 'leadealer_retention_days' );
	delete_option( 'leadealer_delete_data_on_uninstall' );
}

$leadealer_site_ids = is_multisite() ? get_sites( array( 'fields' => 'ids', 'number' => 0 ) ) : array( get_current_blog_id() );

foreach ( $leadealer_site_ids as $leadealer_site_id ) {
	$leadealer_switched = is_multisite() && (int) $leadealer_site_id !== get_current_blog_id();
	if ( $leadealer_switched ) {
		switch_to_blog( (int) $leadealer_site_id );
	}

	leadealer_uninstall_unschedule_site();
	if ( get_option( 'leadealer_delete_data_on_uninstall', 0 ) ) {
		leadealer_uninstall_delete_site_data();
	}

	if ( $leadealer_switched ) {
		restore_current_blog();
	}
}

delete_metadata( 'user', 0, 'leadealer_dismissed_delivery_notice', '', true );
